services:
  backend:
    image: backend
    build:
      context: .
      args:
        - DB_HOST=${DB_HOST}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
        - DB_PORT=${DB_PORT}
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
