/**
 * List of MIME types for different file extensions.
 */
export const MIME_TYPES = [
  { ext: 'aac', type: 'audio/aac' },
  { ext: 'abw', type: 'application/x-abiword' },
  { ext: 'arc', type: 'application/octet-stream' },
  { ext: 'avi', type: 'video/x-msvideo' },
  { ext: 'azw', type: 'application/vnd.amazon.ebook' },
  { ext: 'bin', type: 'application/octet-stream' },
  { ext: 'bz', type: 'application/x-bzip' },
  { ext: 'bz2', type: 'application/x-bzip2' },
  { ext: 'csh', type: 'application/x-csh' },
  { ext: 'css', type: 'text/css' },
  { ext: 'csv', type: 'text/csv' },
  { ext: 'doc', type: 'application/msword' },
  { ext: 'epub', type: 'application/epub+zip' },
  { ext: 'gif', type: 'image/gif' },
  { ext: 'htm', type: 'text/html' },
  { ext: 'html', type: 'text/html' },
  { ext: 'ico', type: 'image/x-icon' },
  { ext: 'ics', type: 'text/calendar' },
  { ext: 'jar', type: 'application/java-archive' },
  { ext: 'jpeg', type: 'image/jpeg' },
  { ext: 'jpg', type: 'image/jpeg' },
  { ext: 'png', type: 'image/png' },
  { ext: 'js', type: 'application/javascript' },
  { ext: 'json', type: 'application/json' },
  { ext: 'mid', type: 'audio/midi' },
  { ext: 'midi', type: 'audio/midi' },
  { ext: 'mpeg', type: 'video/mpeg' },
  { ext: 'mpkg', type: 'application/vnd.apple.installer+xml' },
  { ext: 'odp', type: 'application/vnd.oasis.opendocument.presentation' },
  { ext: 'ods', type: 'application/vnd.oasis.opendocument.spreadsheet' },
  { ext: 'odt', type: 'application/vnd.oasis.opendocument.text' },
  { ext: 'oga', type: 'audio/ogg' },
  { ext: 'ogv', type: 'video/ogg' },
  { ext: 'ogx', type: 'application/ogg' },
  { ext: 'pdf', type: 'application/pdf' },
  { ext: 'ppt', type: 'application/vnd.ms-powerpoint' },
  {
    ext: 'rar',
    type: 'application/x-rar-compressed, application/octet-stream',
  },
  { ext: 'rtf', type: 'application/rtf' },
  { ext: 'sh', type: 'application/x-sh' },
  { ext: 'svg', type: 'image/svg+xml' },
  { ext: 'swf', type: 'application/x-shockwave-flash' },
  { ext: 'tar', type: 'application/x-tar' },
  { ext: 'tif', type: 'image/tiff' },
  { ext: 'tiff', type: 'image/tiff' },
  { ext: 'ttf', type: 'font/ttf' },
  { ext: 'vsd', type: 'application/vnd.visio' },
  { ext: 'wav', type: 'audio/x-wav' },
  { ext: 'weba', type: 'audio/webm' },
  { ext: 'webm', type: 'video/webm' },
  { ext: 'webp', type: 'image/webp' },
  { ext: 'woff', type: 'font/woff' },
  { ext: 'woff2', type: 'font/woff2' },
  { ext: 'xhtml', type: 'application/xhtml+xml' },
  { ext: 'xls', type: 'application/vnd.ms-excel' },
  { ext: 'xlsx', type: 'application/vnd.ms-excel' },
  { ext: 'xml', type: 'application/xml' },
  { ext: 'xul', type: 'application/vnd.mozilla.xul+xml' },
  { ext: 'zip', type: 'application/zip' },
  { ext: '3gp', type: 'video/3gpp' },
  { ext: '3g2', type: 'video/3gpp2' },
  { ext: '7z', type: 'application/x-7z-compressed' },
];
